targets:
  $default:
    sources:     
      - swagger/**
      - lib/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "swagger/"
          output_folder: "lib/swagger_generated_code/"